/*
 * Home page featured-image rotator.
 *
 * The markup it produces is the same markup the year pages ship statically --
 * a .show with stacked .showSlide layers and a .showDots strip -- so the
 * behaviour comes from js/stream.js rather than being reimplemented here:
 * clicking the photograph advances, clicking the caption goes to the gallery,
 * the dots select, hovering pauses, and a reduced-motion request stops the
 * automatic rotation. This file's whole job is choosing the frames and building
 * the slides.
 *
 * The data lives in js/featured-images.json, regenerated by
 * tools/extract-featured.js and tools/add-featured.js, and tinted by
 * tools/sample-featured.js.
 */
(function () {
  'use strict';

  var SLOTS = 10;
  var DATA_URL = 'js/featured-images.json';
  /* How far ahead of the visible frame to have images loaded. All ten slides
     occupy the same place on the page, so marking them lazy achieves nothing --
     the browser considers every one of them to be in the viewport and fetches
     the lot. Two ahead is enough to stay in front of a 3.2s rotation on any
     connection that can show the page at all, and it means a visitor who never
     scrolls or waits pays for three photographs instead of ten. */
  var LOOKAHEAD = 2;

  /* Newer work is favoured, but only mildly. The pool is lopsided by accident
     of how it was assembled -- 2015 and 2017 contribute far more frames than
     the recent years -- so an even draw makes the homepage look like it stopped
     a decade ago. Each frame's weight grows by RECENCY_BASE per year, which
     lifts the newest year to roughly three times the oldest per frame without
     ever excluding the archive.

     Weighted sampling without replacement, via Efraimidis-Spirakis: give each
     item the key random^(1/weight) and take the largest keys. Heavier items
     tend to draw keys closer to 1, and because every item is keyed exactly once
     there is no rejection loop -- the original drew random indices and
     rescanned everything chosen so far, which could spin indefinitely. */
  var RECENCY_BASE = 1.25;

  function yearOf(item) {
    var m = /\/(\d{4})\//.exec(item.gallery || '');
    return m ? +m[1] : 0;
  }

  function rank(items) {
    if (!items.length) return [];

    var oldest = Infinity;
    for (var i = 0; i < items.length; i++) {
      var y = yearOf(items[i]);
      if (y && y < oldest) oldest = y;
    }
    if (oldest === Infinity) oldest = 0;

    var keyed = items.map(function (item) {
      var y = yearOf(item);
      var weight = y ? Math.pow(RECENCY_BASE, y - oldest) : 1;
      /* Math.random() can return 0, whose key is 0 for every weight; nudging it
         off zero keeps the ordering meaningful. */
      return { item: item, key: Math.pow(Math.random() || 1e-9, 1 / weight) };
    });

    keyed.sort(function (a, b) { return b.key - a.key; });

    /* The whole ranking is returned, not just the frames that get shown. The
       tail is the reserve: if a photograph turns out not to be on the server,
       the slide it was in takes the next item from it rather than sitting there
       as a broken image. Ranking everything once means a replacement is drawn
       from the same weighted order as the original pick. */
    return keyed.map(function (k) {
      return k.item;
    });
  }

  /* The pool records a venue as it appears in the catalog -- "WaMu Theater,
     Seattle, WA" -- but every photograph on the site is from the same place, so
     the city is noise on a caption this small. The year pages drop it at build
     time; this does the same at runtime. */
  function venueOnly(venue) {
    return String(venue || '').replace(/,\s*[^,]+,\s*[A-Z]{2}\s*$/, '').trim();
  }

  function el(tag, className) {
    var n = document.createElement(tag);
    if (className) n.className = className;
    return n;
  }

  function fillSlide(slide, item, eager) {
    if (item.cap) {
      slide.style.setProperty('--cap-top', item.cap[0]);
      slide.style.setProperty('--cap-bot', item.cap[1]);
      slide.style.setProperty('--cap-fg', item.cap[2]);
    } else {
      slide.style.removeProperty('--cap-top');
      slide.style.removeProperty('--cap-bot');
      slide.style.removeProperty('--cap-fg');
    }

    var img = slide.querySelector('img');
    img.width = item.width || 640;
    img.height = item.height || 426;
    img.alt = item.artist || '';
    img.removeAttribute('data-src');
    if (eager) {
      img.src = item.image;
    } else {
      img.removeAttribute('src');
      img.setAttribute('data-src', item.image);
    }

    var caption = slide.querySelector('.showCaption');
    caption.href = item.gallery;
    while (caption.firstChild) caption.removeChild(caption.firstChild);

    var artist = el('span', 'showArtist');
    artist.textContent = item.artist || '';
    caption.appendChild(artist);

    var venue = venueOnly(item.venue);
    if (venue) {
      var v = el('span', 'showVenue');
      v.textContent = venue;
      caption.appendChild(v);
    }
    if (item.date) {
      var d = el('span', 'showDate');
      d.textContent = item.date;
      caption.appendChild(d);
    }
  }

  function buildSlide(item, index) {
    var slide = el('div', 'showSlide' + (index === 0 ? ' is-active' : ''));
    if (index !== 0) slide.setAttribute('aria-hidden', 'true');

    var img = el('img');
    img.decoding = 'async';
    if (index === 0) img.setAttribute('fetchpriority', 'high');
    slide.appendChild(img);

    var caption = el('a', 'showCaption');
    if (index !== 0) caption.tabIndex = -1;
    slide.appendChild(caption);

    fillSlide(slide, item, index === 0);
    return slide;
  }

  function dotLabel(index, item) {
    return 'Show photo ' + (index + 1) + ': ' + ((item && item.artist) || '');
  }

  function hydrate(frame) {
    var slides = frame.querySelectorAll('.showSlide');
    /* The MutationObserver that calls this runs as a microtask, so it can fire
       after the frame it was queued for has already been emptied by a slide
       being dropped. Without this the modulo below divides by zero and the
       lookahead indexes past the end. */
    if (!slides.length) return;
    var active = 0;
    for (var i = 0; i < slides.length; i++) {
      if (slides[i].classList.contains('is-active')) active = i;
    }
    for (var n = 0; n <= LOOKAHEAD; n++) {
      var img = slides[(active + n) % slides.length].querySelector('img[data-src]');
      if (img) {
        img.src = img.getAttribute('data-src');
        img.removeAttribute('data-src');
      }
    }
  }

  function init(items) {
    var show = document.getElementById('focusShow');
    var frame = document.getElementById('focusFrame');
    var dotHost = show && show.querySelector('.showDots');
    if (!show || !frame || !items || !items.length) return;

    var ranked = rank(items);
    var slots = ranked.slice(0, SLOTS);
    /* Everything the pick did not use, kept in the same weighted order, ready
       to stand in for a frame whose photograph turns out to be missing. */
    var reserve = ranked.slice(SLOTS);
    var showing = slots.slice();

    /* A frame in the pool can name a photograph that is not on the server. The
       pool is generated from the local archive, and the archive is published
       separately from the markup, so an event that has not been uploaded yet
       is listed here and 404s when the browser asks for it. That used to put a
       broken image in the middle of the homepage, which is a worse failure
       than the missing photograph itself: it is the first thing a visitor
       sees, and it looks like the site is broken rather than one gallery being
       incomplete. Swapping in the next ranked frame instead means the rotator
       degrades to a slightly smaller pool and nothing shows. */
    function onImageError(e) {
      var slide = e.target.parentNode;
      var i = Array.prototype.indexOf.call(frame.children, slide);
      if (i < 0) return;

      if (reserve.length) {
        var next = reserve.shift();
        showing[i] = next;
        fillSlide(slide, next, true);
        if (dotHost && dotHost.children[i]) {
          dotHost.children[i].setAttribute('aria-label', dotLabel(i, next));
        }
        return;
      }
      dropSlide(i);
    }

    function dropSlide(i) {
      var slide = frame.children[i];
      if (!slide) return;
      var wasActive = slide.classList.contains('is-active');

      frame.removeChild(slide);
      showing.splice(i, 1);
      if (dotHost && dotHost.children[i]) dotHost.removeChild(dotHost.children[i]);
      if (dotHost) {
        for (var n = 0; n < dotHost.children.length; n++) {
          dotHost.children[n].setAttribute('data-index', String(n));
          dotHost.children[n].setAttribute('aria-label', dotLabel(n, showing[n]));
        }
      }

      if (!frame.children.length) {
        show.setAttribute('hidden', '');
        return;
      }
      if (wasActive) {
        var take = frame.children[i] || frame.children[0];
        var at = Array.prototype.indexOf.call(frame.children, take);
        take.classList.add('is-active');
        take.removeAttribute('aria-hidden');
        if (dotHost && dotHost.children[at]) {
          dotHost.children[at].setAttribute('aria-selected', 'true');
        }
      }
      if (frame.children.length < 2) show.classList.remove('has-rotator');
      hydrate(frame);
    }

    slots.forEach(function (item, i) {
      var slide = buildSlide(item, i);
      slide.querySelector('img').addEventListener('error', onImageError);
      frame.appendChild(slide);
    });

    if (dotHost && slots.length > 1) {
      slots.forEach(function (item, i) {
        var dot = el('button');
        dot.type = 'button';
        dot.setAttribute('role', 'tab');
        dot.setAttribute('data-index', String(i));
        dot.setAttribute('aria-selected', String(i === 0));
        dot.setAttribute('aria-label', dotLabel(i, item));
        dotHost.appendChild(dot);
      });
    }

    if (slots.length > 1) show.classList.add('has-rotator');
    show.removeAttribute('hidden');

    /* Whatever moves the rotator -- a click, a dot, the ambient timer in
       stream.js -- ends up toggling is-active, so watching for that is enough
       to keep the loading window ahead of it without this file needing to know
       when any of them happen. */
    if (window.MutationObserver) {
      new MutationObserver(function () { hydrate(frame); })
        .observe(frame, { subtree: true, attributes: true, attributeFilter: ['class'] });
    }
    hydrate(frame);

    if (window.dcStream && window.dcStream.refresh) window.dcStream.refresh();
  }

  function load() {
    fetch(DATA_URL, { cache: 'no-cache' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(init)
      .catch(function (err) {
        // The rest of the page is unaffected; the rotator simply stays hidden.
        if (window.console) console.error('Featured rotator failed to load:', err);
      });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', load);
  } else {
    load();
  }
})();
