/*
 * Home page featured-image rotator.
 *
 * Replaces the original js/homerotate.js, which carried 20 KB of hard-coded
 * gallery data inline. That data now lives in js/featured-images.json and is
 * regenerated by tools/extract-featured.js.
 *
 * Behavioural notes:
 *  - Rotation stops when the tab is hidden and resumes when it returns, so a
 *    backgrounded tab no longer downloads photos nobody is looking at.
 *  - Honours prefers-reduced-motion: users who ask for reduced motion get a
 *    single static image and the manual dots, but no automatic rotation.
 *  - The featured image is now a link to its gallery. Previously it was inert,
 *    even though the gallery URL was already in the data.
 */
(function () {
  'use strict';

  var SLOTS = 10;
  var INTERVAL_MS = 4000;
  var DATA_URL = 'js/featured-images.json';

  var els = {};
  var slots = [];
  var current = -1;
  var timer = null;
  var rotating = false;

  var reduceMotion =
    window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function $(id) {
    return document.getElementById(id);
  }

  /* Fisher-Yates. The original drew random indices and rejected duplicates by
     rescanning everything chosen so far, which could loop indefinitely. */
  function pick(items, count) {
    var pool = items.slice();
    for (var i = pool.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var t = pool[i];
      pool[i] = pool[j];
      pool[j] = t;
    }
    return pool.slice(0, Math.min(count, pool.length));
  }

  function show(index) {
    var item = slots[index];
    if (!item) return;

    if (current >= 0 && els.dots[current]) {
      els.dots[current].className = 'circle';
      els.dots[current].setAttribute('aria-selected', 'false');
    }

    els.image.src = item.image;
    els.image.alt = item.artist + ' at ' + item.venue + ', ' + item.date;
    els.artist.textContent = item.artist;
    els.venue.textContent = ' at ' + item.venue;
    els.date.textContent = item.date;

    if (els.link) els.link.href = item.gallery;

    if (els.dots[index]) {
      els.dots[index].className = 'circle circleSelected';
      els.dots[index].setAttribute('aria-selected', 'true');
    }

    els.container.style.visibility = 'visible';
    current = index;
  }

  function advance() {
    show((current + 1) % slots.length);
  }

  function start() {
    if (reduceMotion || rotating || slots.length < 2) return;
    rotating = true;
    timer = window.setInterval(advance, INTERVAL_MS);
  }

  function stop() {
    rotating = false;
    if (timer !== null) {
      window.clearInterval(timer);
      timer = null;
    }
  }

  function init(items) {
    if (!items.length) return;

    els.container = $('focusContainer');
    els.image = $('focusImage');
    els.artist = $('focusArtist');
    els.venue = $('focusVenue');
    els.date = $('focusDate');
    els.link = $('focusLink');
    els.dots = [];

    if (!els.container || !els.image) return;

    slots = pick(items, SLOTS);

    var dotHost = document.querySelector('.circlesContainer');
    if (dotHost) {
      dotHost.innerHTML = '';
      dotHost.setAttribute('role', 'tablist');
      dotHost.setAttribute('aria-label', 'Featured photo');

      slots.forEach(function (item, i) {
        var dot = document.createElement('button');
        dot.type = 'button';
        dot.className = 'circle';
        dot.id = 'circle' + i;
        dot.setAttribute('role', 'tab');
        dot.setAttribute('aria-selected', 'false');
        dot.setAttribute('aria-label', 'Show photo ' + (i + 1) + ': ' + item.artist);
        dot.addEventListener('click', function () {
          stop();
          show(i);
        });
        dotHost.appendChild(dot);
        els.dots.push(dot);
      });
    }

    show(0);
    start();

    // Any navigation away should stop the rotation so a click is never stolen
    // by an image swapping underneath it.
    document.addEventListener('click', function (e) {
      if (e.target && e.target.closest && e.target.closest('a')) stop();
    });

    document.addEventListener('visibilitychange', function () {
      if (document.hidden) {
        stop();
      } else {
        start();
      }
    });
  }

  function load() {
    fetch(DATA_URL, { cache: 'no-cache' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(init)
      .catch(function (err) {
        // The rest of the page is unaffected; the rotator simply stays hidden.
        if (window.console) console.error('Featured rotator failed to load:', err);
      });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', load);
  } else {
    load();
  }
})();
